# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &auditor
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: auditorMSP

        # ID to load the MSP definition as
        ID: auditorMSP

        MSPDir: ../organizations/peerOrganizations/auditor.supply-chain.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('auditorMSP.admin', 'auditorMSP.peer', 'auditorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('auditorMSP.admin', 'auditorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('auditorMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('auditorMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.auditor.supply-chain.com
              Port: 11051
